
services:
  web:
    image: my-flask-app:multistage
    ports:
      - "5002:5002"
    depends_on:
      - mydb
 
  mydb:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pwd