
services:
  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
 
  mydb:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw